# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/doublet_data/hitgraphs_med_000
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_data/hitgraphs_med
n_graphs: 2000

# Doublet trainer model
doublet_model_dir: /global/cscratch1/sd/danieltm/ExaTrkX/doublet_results/agnn03

# Graph building configuration
selection:
    pt_min: 1 # GeV
    phi_slope_max: 0.001
    z0_max: 200
    n_phi_sections: 4
    n_eta_sections: 1
    eta_range: [-5, 5]
