# Input/output configuration
input_dir:  /global/cscratch1/sd/danieltm/ExaTrkX/trackml/train_all
output_dir:  /global/cscratch1/sd/danieltm/ExaTrkX/counter_data/hitgraphs_small_000
n_files: 100

# Graph building configuration
selection:
    pt_min: 1 # GeV
    phi_slope_max: 0.0006
    z0_max: 150
    n_phi_sections: 4
    n_eta_sections: 8
    eta_range: [-1, 1]
