# Input/output configuration
input_dir:  /global/cscratch1/sd/danieltm/ExaTrkX/trackml/train_all
output_dir:  /global/cscratch1/sd/danieltm/ExaTrkX/doublet_results/hitgraphs_high_000
n_files: 8192

# Graph building configuration
selection:
    pt_min: 0.5 # GeV
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 8
    n_eta_sections: 1
    eta_range: [-2, 2]
