output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_results/checkpoints_med/agnn02

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_data/hitgraphs_med
    n_train: 1920 #57344
    n_valid: 80
    real_weight: 3. #6.25  # 0.5 / 0.08
    batch_size: 4
    n_workers: 4

model:
    name: tripgnn
    input_dim: 7
    hidden_dim: 64
    n_graph_iters: 3
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam #SGD
    #momentum: 0.9
    learning_rate: 0.01
    lr_scaling: sqrt
    lr_warmup_epochs: 5
    lr_decay_schedule:
        - {start_epoch: 10, end_epoch: 25, factor: 0.5}
        - {start_epoch: 25, end_epoch: 40, factor: 0.01}
        - {start_epoch: 40, end_epoch: 50, factor: 0.005}
        - {start_epoch: 50, end_epoch: 64, factor: 0.001}

training:
    n_epochs: 64
