output_dir: /mnt/c/Users/Daniel/Dropbox/Research/Publications/ExaTrkX/results/agnn01

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: /mnt/c/Users/Daniel/Dropbox/Research/Publications/ExaTrkX/data/hitgraphs_tiny
    n_train: 10 #57344
    n_valid: 1
    real_weight: 5 #6.25  # 0.5 / 0.08
    batch_size: 1
    n_workers: 1

model:
    name: tripgnn
    input_dim: 3
    hidden_dim: 64
    n_graph_iters: 8
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam #SGD
    #momentum: 0.9
    learning_rate: 0.001
    lr_scaling: sqrt
    lr_warmup_epochs: 5
    lr_decay_schedule:
        - {start_epoch: 10, end_epoch: 15, factor: 0.1}
        - {start_epoch: 15, end_epoch: 20, factor: 0.01}

training:
    n_epochs: 10
